spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  threads:
    virtual:
      enabled: true


  h2:
    console:
      enabled: true

  # Redis 설정은 RedisTestContainersConfig에서 TestContainer로 대체됨
  data:
    redis:
      host: localhost
      port: 6379
      password:
      local: true

  mail:
    host: smtp.gmail.com
    username: qkenrdl05@gmail.com
    password: pfmd qump wwmk lszw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jwt:
    token:
      access-expiration-time: 1800000  # 30분 (밀리초)
      refresh-expiration-time: 604800000  # 7일 (밀리초)
      secret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey

aws:
  access-key: accesskey
  secret-key: secretkey
  region: ap-northeast-2
  s3:
    bucket: bucket
  dynamodb:
    endpoint: http://localhost:8000
  cloudfront:
    domain: https://d2lmyznn5nj2bl.cloudfront.net/

decorator:
  datasource:
    p6spy:
      enable-logging: false

logging:
  config: classpath:logs/logback-local.xml

security:
  cors:
    allowed-origins: http://localhost:8080
    allowed-origins-https: https://localhost:443
    allowed-origins-client: http://localhost:3000