spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
  mail:
    host: smtp.gmail.com
    username: qkenrdl05@gmail.com
    password: pfmd qump wwmk lszw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jwt:
    token:
      access-expiration-time: 1800000  # 30분 (밀리초)
      refresh-expiration-time: 604800000  # 7일 (밀리초)

aws:
  access-key: accesskey
  secret-key: secretkey
  region: ap-northeast-2
  s3:
    bucket: bucket
  dynamodb:
    endpoint: http://localhost:8000

decorator:
  datasource:
    p6spy:
      enable-logging: false

logging:
  level:
    org:
      springframework:
        jdbc: debug
